### ISSUE TITLE
OSA [1582272]: Restart plays not correctly defined when upgrade.sh fails

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1079]
##### What version (commit) do you encounter this issue on?

r12.1.1

##### What type of issue is this (bug, feature, documentation, regression)?

Bug

##### What is the expected behavior?

Proper output where to continue

##### What is actually happening?

```
ran setup-infrastructure.yml -e 'galera_upgrade=true' -e 'rabbitmq_upgrade=true'
******************** failure ********************
The upgrade script has encountered a failure.
Failed on task setup-infrastructure.yml -e 'galera_upgrade=true' -e 'rabbitmq_upgrade=true'
Re-run the run-upgrade.sh script, or
execute the remaining tasks manually:
openstack-ansible  -e 'pip_install_options=--force-reinstall'
openstack-ansible  -e 'pip_install_options=--force-reinstall'
openstack-ansible  -e 'pip_install_options=--force-reinstall'
openstack-ansible  -e 'pip_install_options=--force-reinstall'
openstack-ansible setup-hosts.yml --limit '!galera_all[0]' -e 'pip_install_options=--force-reinstall'
openstack-ansible lxc-containers-create.yml --limit galera_all[0] -e 'pip_install_options=--force-reinstall'
openstack-ansible  -e 'pip_install_options=--force-reinstall'
openstack-ansible setup-infrastructure.yml -e 'galera_upgrade=true' -e 'rabbitmq_upgrade=true' -e 'pip_install_options=--force-reinstall'
openstack-ansible /opt/rpc-openstack/openstack-ansible/scripts/upgrade-utilities/playbooks/disable-neutron-port-security.yml -e 'pip_install_options=--force-reinstall'
openstack-ansible /opt/rpc-openstack/openstack-ansible/scripts/upgrade-utilities/playbooks/memcached-flush.yml -e 'pip_install_options=--force-reinstall'
openstack-ansible setup-openstack.yml -e 'pip_install_options=--force-reinstall'
openstack-ansible /opt/rpc-openstack/openstack-ansible/scripts/upgrade-utilities/playbooks/cleanup-rabbitmq-vhost.yml -e 'pip_install_options=--force-reinstall'
******************** failure ********************
```

##### How can we reproduce this issue?

Create failure within repo build process

##### How can we verify your issue is addressed?

If repo build process fails or any other setup-infrastructure.yml task, it does not print out useless statements like

```
openstack-ansible  -e 'pip_install_options=--force-reinstall'
```

Or already completed checks
```
openstack-ansible setup-hosts.yml --limit '!galera_all[0]' -e 'pip_install_options=--force-reinstall'
openstack-ansible lxc-containers-create.yml --limit galera_all[0] -e 'pip_install_options=--force-reinstall'
openstack-ansible  -e 'pip_install_options=--force-reinstall'
```

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

prio 1

##### What is your evaluation on the importance of this issue, and why?

Upgrade process is not reliable

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master
- [x] liberty-12.2 https://github.com/rcbops/rpc-openstack/pull/1371

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [x] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by git-harry** [comment]
Require's bug logged on Launchpad.

**Comment by BjoernT** [comment]
FYI,

I saw in the logs that the previous, successful ran plays, got marked as successful, but still have been included in the output as plays to run:

```
setup-hosts.yml --limit '!galera_all[0]' has been marked as success
lxc-containers-create.yml --limit galera_all[0] has been marked as success
```

**Comment by BjoernT** [comment]
Opened OSA bug https://bugs.launchpad.net/openstack-ansible/+bug/1582272

**Comment by BjoernT** [comment]
As additional requirements, we need to print out the RPC-O steps, they are always missing and easily forgotten

**Comment by b3rnard0** [comment]
@Frank-ZhangXin Please provide an update on this issue. Thanks.

**Comment by Frank-ZhangXin** [comment]
@b3rnard0 This bug is assigned to me with @sigmavirus24  as on-boarding pairing program bug. Currently I found run-upgrade.sh is updated since liberty branch by @sigmavirus24 , and it might already patched this bug. But we need to verify it soon.

**Comment by Frank-ZhangXin** [comment]
Update: 
we basically fixed the task array issue which causes playbook name misplaced when re-run run-upgrade.sh script. To be simple, task array is supposed to remove accomplished task(s) and start from the very spot where previous exception happened. The bug happened because upgrade script doesn't treats completed tasks well and additionally leaves empty entries existing in the array, which eventually makes misplacement of succeeding tasks. I have some problem to submit our fix to gerrit review, and fixing it now.

**Comment by Frank-ZhangXin** [comment]
Update: patch has been submitted and waiting for review: https://review.openstack.org/#/c/352488/

**Comment by Frank-ZhangXin** [comment]
Update: jenkins rabbitmq container building failed, though it's one unrelated to my changes. Rerun the check already.

**Comment by Frank-ZhangXin** [comment]
Update: jenkins ubuntu trusty test failed, rechecking. And listened to @prometheanfire advice, I changed commit message and comment in script a lot. So everything becomes clear and easy to understand for user.

**Comment by Frank-ZhangXin** [comment]
Update: jenkins test passed, and needs to be reviewed and be merged. Link: https://review.openstack.org/#/c/352488/

**Comment by BjoernT** [comment]
@Frank-ZhangXin This requirement is still open:

As additional requirements, we need to print out the RPC-O steps, they are always missing and easily forgotten

**Comment by git-harry** [comment]
@BjoernT there is a separate issue to track that - https://github.com/rcbops/rpc-openstack/issues/1300

**Comment by Frank-ZhangXin** [comment]
Update: Jenkins keeps failed with unknown reason, we'll continue track it and recheck.

@BjoernT what kind of requirement do you mention about? If you mean this bug, we're still working on testing here https://review.openstack.org/#/c/352488/.

**Comment by b3rnard0** [comment]
We will need additional help on this next week.

**Comment by BjoernT** [comment]
@Frank-ZhangXin #1300 so if want to split it up in multiple bugs, that's fine but both should be fixed in time since the rpc-o upgrade steps are quite easily forgotten, see https://github.com/rcbops/rpc-openstack/blob/liberty-12.2/scripts/upgrade.sh#L56-L61 those will never be executed when the previous run-upgrade.sh  fails

**Comment by hughsaunders** [comment]
Can't find anything that needs reviewing here.

**Comment by Frank-ZhangXin** [comment]
@BjoernT OK, I'll take a look at #1300 , but this week is a little busy with trainings.

**Comment by git-harry** [comment]
stable/mitaka - https://review.openstack.org/#/c/358641/ has merged upstream and is now in RPCO master. It is not yet in mitaka-13.0 but is not required in that branch.
liberty - https://review.openstack.org/#/c/360385/ in review

I have created https://github.com/rcbops/rpc-openstack/pull/1357 to test that the patch up for review for liberty does not break our upgrade check.

**Comment by git-harry** [comment]
https://review.openstack.org/#/c/360385/ has merged. Now I believe we just require a SHA update. @Frank-ZhangXin are you happy for this to be moved to pending-sha-update or is there something else you still need to do?

**Comment by sigmavirus24** [comment]
I would agree this just needs a SHA update and is no longer blocked.
