### ISSUE TITLE
Conflicting Tempest pip package versions

### ISSUE THREAD

**Issue by jpmontez** [rcbops/rpc-openstack#1119]
##### What version (commit) do you encounter this issue on?
r12.2.0rc3

##### What type of issue is this (bug, feature, documentation, regression)?
Bug

##### What is the expected behavior?
The correct package version requirements and dependencies be installed.

##### What is actually happening?
The `oslo.log` package installed is too recent and isn't the version required in the `requirements.txt` file.

```
${PYTHON:-python} -m subunit.run discover -t ${OS_TOP_LEVEL:-./} ${OS_TEST_PATH:-./tempest/test_discover} --list 
--- import errors ---
Failed to import test module: tempest.test_discover.test_discover
Traceback (most recent call last):
  File "/opt/tempest_0e25a90793a17728ab235d21ee282db31add3d74/lib/python2.7/site-packages/unittest2/loader.py", line 456, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/tempest_0e25a90793a17728ab235d21ee282db31add3d74/lib/python2.7/site-packages/unittest2/loader.py", line 395, in _get_module_from_name
    __import__(name)
  File "/opt/tempest_0e25a90793a17728ab235d21ee282db31add3d74/tempest/test_discover/test_discover.py", line 18, in <module>
    from tempest.test_discover import plugins
  File "/opt/tempest_0e25a90793a17728ab235d21ee282db31add3d74/tempest/test_discover/plugins.py", line 21, in <module>
    from tempest.lib.common.utils import misc
  File "/opt/tempest_0e25a90793a17728ab235d21ee282db31add3d74/tempest/lib/common/utils/misc.py", line 19, in <module>
    from oslo_log import log as logging
  File "/opt/tempest_0e25a90793a17728ab235d21ee282db31add3d74/lib/python2.7/site-packages/oslo_log/log.py", line 49, in <module>
    from oslo_log import _options
  File "/opt/tempest_0e25a90793a17728ab235d21ee282db31add3d74/lib/python2.7/site-packages/oslo_log/_options.py", line 38, in <module>
    help='If set to true, the logging level will be set to '
  File "/opt/tempest_0e25a90793a17728ab235d21ee282db31add3d74/lib/python2.7/site-packages/oslo_config/cfg.py", line 982, in __init__
    super(BoolOpt, self).__init__(name, type=types.Boolean(), **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mutable'
```

It’s caused by a pip package conflict between what’s being loaded in the installed virtualenv (version 3.7.0):

```
(tempest_0e25a90793a17728ab235d21ee282db31add3d74)root@697188-infra01_utility_container-a012b479:~# pip freeze | grep oslo.log
oslo.log==3.7.0
```

And the version actually required by the Tempest library (library SHA: 0e25a90):

```
root@697188-infra01_utility_container-a012b479:/opt/tempest_0e25a90793a17728ab235d21ee282db31add3d74# grep 'oslo.log' requirements.txt
oslo.log>=1.14.0 # Apache-2.0
```

##### How can we reproduce this issue?
By running an installation of r12.2.0rc3 on a multi-node environment.

##### How can we verify your issue is addressed?
It's present in the QE-IAD3-LAB03 environment provided by Dennis: http://jenkins.openstack-ansible.com/job/RPC-OA/140/

It's also been see in the daily gating jobs.

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

Find a container that has the packages installed correctly and run Tempest tests there.

##### What is your evaluation on the importance of this issue, and why?
Gating utilities are inconsistently installed which slows QE and pull requests for the development team.

##### What branches / milestones do you believe this issue should target?
12.2.0

###### Remove branches (lines) you do not wish to target.
- [x] Master https://review.openstack.org/#/c/310766/
- [x] Mitaka https://review.openstack.org/#/c/341362/
- [ ] liberty-12.2 https://review.openstack.org/#/c/347488

**Comment by git-harry** [comment]
This also impacts dev testing. This issue does not directly impact customers but primarily affects testing by forcing rechecks. This does not block the release and seems like a prio-2 issue to me.

**Comment by d34dh0r53** [comment]
This may be related to #1120 in that Tempest will need it's own venv.

**Comment by hughsaunders** [comment]
upstream bug: https://bugs.launchpad.net/openstack-ansible/+bug/1592509

**Comment by hughsaunders** [comment]
As noted in upstream bug, this is fixed in master.

**Comment by hughsaunders** [comment]
liberty backport: https://review.openstack.org/#/c/347488

**Comment by hughsaunders** [comment]
The liberty patch is now a minimal bugfix rather than a full backport.

**Comment by b3rnard0** [comment]
@git-harry Same with this one, this is a gating bug, not a gating feature.
