### ISSUE TITLE
OSA [1590166]: Rejoining/recovery of galera cluster fails Edit

### ISSUE THREAD

**Issue by b3rnard0** [rcbops/rpc-openstack#1128]
##### What version (commit) do you encounter this issue on?

TBD

##### What type of issue is this (bug, feature, documentation, regression)?

bug

##### What is the expected behavior?

See https://bugs.launchpad.net/openstack-ansible/+bug/1590166

##### What is actually happening?

See https://bugs.launchpad.net/openstack-ansible/+bug/1590166

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

See https://bugs.launchpad.net/openstack-ansible/+bug/1590166

##### How can we reproduce this issue?

See https://bugs.launchpad.net/openstack-ansible/+bug/1590166

##### How can we verify your issue is addressed?

See https://bugs.launchpad.net/openstack-ansible/+bug/1590166

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

See https://bugs.launchpad.net/openstack-ansible/+bug/1590166

##### What is your evaluation on the importance of this issue, and why?

See https://bugs.launchpad.net/openstack-ansible/+bug/1590166

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master https://github.com/rcbops/rpc-openstack/pull/1352
- [x] mitaka-13.0 https://github.com/rcbops/rpc-openstack/pull/1373
- [x] liberty-12.2 https://github.com/rcbops/rpc-openstack/pull/1321

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [x] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by b3rnard0** [comment]
We will need more details so that we can start tracking this issue. cc: @BjoernT @git-harry

**Comment by mancdaz** [comment]
Discussion has occurred in the OSA bug, as well as internally with DBA group on ML. We are currently looking into the conditions which may have caused this bug to manifest, but the likelyhood is that this was a one off occurrence and not something we can fix in OSA or RPCO.

Given the isolated occurrence and difficulty in reproducing, I am making this a prio-3.

**Comment by mancdaz** [comment]
After much digging, our DBA has concluded that this is a bug caused by the use of the  --compact option. Given that this option is "pretty useless in many environments", his recommendation is to disable this option to fix the bug.

Since this is a fix that must go into OSA, we will need to track the fix(es) here.

**Comment by mancdaz** [comment]
Master OSA review: https://review.openstack.org/#/c/355451/

**Comment by b3rnard0** [comment]
@mancdaz should this be in the Pending SHA update column?
