### ISSUE TITLE
OSA [1565128]: mariadb10 libs are needed when building the repo

### ISSUE THREAD

**Issue by b3rnard0** [rcbops/rpc-openstack#1132]
##### What version (commit) do you encounter this issue on?

Master

##### What type of issue is this (bug, feature, documentation, regression)?

bug

##### What is the expected behavior?

See https://bugs.launchpad.net/openstack-ansible/+bug/1565128

##### What is actually happening?

https://bugs.launchpad.net/openstack-ansible/+bug/1565128

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

https://bugs.launchpad.net/openstack-ansible/+bug/1565128

##### How can we reproduce this issue?

https://bugs.launchpad.net/openstack-ansible/+bug/1565128

##### How can we verify your issue is addressed?

https://bugs.launchpad.net/openstack-ansible/+bug/1565128

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

https://bugs.launchpad.net/openstack-ansible/+bug/1565128

##### What is your evaluation on the importance of this issue, and why?

https://bugs.launchpad.net/openstack-ansible/+bug/1565128

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [x] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by b3rnard0** [comment]
We will need more details so that we can start tracking this issue.

cc: @BjoernT @git-harry

**Comment by alextricity25** [comment]
I poked the bug reporter for more info on the OSA bug report:
https://bugs.launchpad.net/openstack-ansible/+bug/1565128

Things seemingly look okay on liberty, but I would like to find out some more information from OP to see if he had his environment set up in such a way that would cause this bug to manifest.

**Comment by alextricity25** [comment]
Patch set has been submitted to the liberty branch and is ready for review.
https://review.openstack.org/#/c/348533/

**Comment by alextricity25** [comment]
Updates can be viewed here:
https://bugs.launchpad.net/openstack-ansible/+bug/1565128

**Comment by alextricity25** [comment]
PR for this is ready for review

**Comment by mancdaz** [comment]
OSA review for liberty has merged
