### ISSUE TITLE
OSA [1491486]: Cinder API cannot show more than 1000 rows

### ISSUE THREAD

**Issue by b3rnard0** [rcbops/rpc-openstack#1133]
##### What version (commit) do you encounter this issue on?

Master

##### What type of issue is this (bug, feature, documentation, regression)?

bug

##### What is the expected behavior?

See https://bugs.launchpad.net/openstack-ansible/+bug/1491486

##### What is actually happening?

See https://bugs.launchpad.net/openstack-ansible/+bug/1491486

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

See https://bugs.launchpad.net/openstack-ansible/+bug/1491486

##### How can we reproduce this issue?

See https://bugs.launchpad.net/openstack-ansible/+bug/1491486

##### How can we verify your issue is addressed?

See https://bugs.launchpad.net/openstack-ansible/+bug/1491486

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

See https://bugs.launchpad.net/openstack-ansible/+bug/1491486

##### What is your evaluation on the importance of this issue, and why?

See https://bugs.launchpad.net/openstack-ansible/+bug/1491486

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by b3rnard0** [comment]
We will need more details so that we can start tracking this issue.

cc: @BjoernT @git-harry

**Comment by nategraf** [comment]
@git-harry : The upstream bug is marked as "invalid" for Kilo and Trunk and "won't fix" for Juno with no mention of the newer branches. (It was submitted about 10 months ago) What should we do with this issue?

**Comment by git-harry** [comment]
@nategraf my (possibly incorrect) understanding is that this should be configurable with a var. What I would suggest is that you confirm if this is still a valid issue for our supported branches. If it is not valid we need to communicate with support how to fix it. This may include a docs update. If it is valid we need to work out where the fix needs to live and if upstream make sure there is a valid issue and we fix it if possible.

In addition, we no longer provide development support to Juno so you don't need to worry about that one.

**Comment by git-harry** [comment]
I've removed the blocked label based on my previous comment. @nategraf if you still think this should be blocked let me know and we can discuss.

**Comment by nategraf** [comment]
I looked into this issue a little further and spoke with support.
A) This is actually not a bug in openstack-ansible. It is a feature of cinder cli [1] which was not implemented until Kilo.
B) Any environments using Kilo or later will not experience this issue.
C) There is at least one customer using Juno with over 1000 volumes, and they are seeing this issue.
D) There is a workaround, which is to pull the volume data directly from the database.

@git-harry  based on this information is this a bug we are going to pursue fixing?

[1]
https://blueprints.launchpad.net/cinder/+spec/cinder-pagination
https://bugs.launchpad.net/cinder/+bug/1342192

**Comment by nategraf** [comment]
Closed based on this bug only effecting Juno, which is EOL. 
For environments which will not be upgrading to Kilo or later, query the database directly to get a complete list of volumes.
