### ISSUE TITLE
OSA [1588051]: Excessive logging to /var/log in neutron agents and other containers

### ISSUE THREAD

**Issue by b3rnard0** [rcbops/rpc-openstack#1143]
##### What version (commit) do you encounter this issue on?

Master

##### What type of issue is this (bug, feature, documentation, regression)?

bug

##### What is the expected behavior?

See https://bugs.launchpad.net/openstack-ansible/+bug/1588051

##### What is actually happening?

See https://bugs.launchpad.net/openstack-ansible/+bug/1588051

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

See https://bugs.launchpad.net/openstack-ansible/+bug/1588051

##### How can we reproduce this issue?

See https://bugs.launchpad.net/openstack-ansible/+bug/1588051

##### How can we verify your issue is addressed?

See https://bugs.launchpad.net/openstack-ansible/+bug/1588051

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

See https://bugs.launchpad.net/openstack-ansible/+bug/1588051

##### What is your evaluation on the importance of this issue, and why?

See https://bugs.launchpad.net/openstack-ansible/+bug/1588051

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master (https://review.openstack.org/#/c/351182/ )
- [ ] liberty-12.2 (https://review.openstack.org/#/c/351184/)

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by b3rnard0** [comment]
We will need more details so that we can start tracking this issue. cc: @BjoernT @git-harry

**Comment by ameserole** [comment]
UPDATE:
A patch has been submitted to master for review
https://review.openstack.org/#/c/350697/

**Comment by git-harry** [comment]
350679 has now merged, backports still required.

**Comment by ameserole** [comment]
UPDATE:
Backports have been submitted:
https://review.openstack.org/#/c/351182/ (Mitaka)
https://review.openstack.org/#/c/351184/ (Liberty)

**Comment by ameserole** [comment]
@git-harry @BjoernT I added two more issues to keep track of the separate fixes that were suggested in the original bug report. The bug that I fixed with this card is only the syslog leakage issue pointed out.

https://github.com/rcbops/rpc-openstack/issues/1292
https://github.com/rcbops/rpc-openstack/issues/1291
