### ISSUE TITLE
Current AIO configurations drop instance traffic to heat metadata url

### ISSUE THREAD

**Issue by alextricity25** [rcbops/rpc-openstack#1167]
##### What version (commit) do you encounter this issue on?
master
##### What type of issue is this (bug, feature, documentation, regression)?
bug
##### What is the expected behavior?
Instances should be able to communicate to the heat metadata url.

##### What is actually happening?
Spinning up a heat template that utilizes the software-deployment resource will fail. This is because the resource requires the instance to communicate to the heat metadata url, but can't due to incorrect packet checksums that appear on an AIO. It is essentially the same problem as:
https://github.com/rcbops/rpc-openstack/blob/master/scripts/deploy.sh#L179-L183

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
I was doing some testing by creating basic heat stack that spins up a server and uses software-deployments/configs to run a trivial script.

##### How can we reproduce this issue?
Use the following heat template to create a heat stack on an AIO. Note a private network name 'test-network' must be created.
```
heat_template_version: 2015-04-30

description: Simple template to deploy a single compute instance

parameters:
  keyname:
    type: string
    label: Salt-Master Keyname.
    description: The name of the key that should be used to ssh into the Salt-Master.

  image:
    type: string
    label: Image Name
    description: Name of the existing image to use for every vm spun up by this stack. The image should have heat-config and heat-config-script baked in.

  flavor:
    type: string
    label: Flavor
    description: Flavor of all vms. This may be changed in the future to allow different flavors for the different vms in this stack.
    default: m1.small

resources:
  config-salt-master:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      outputs:
        - name: result
          type: Json
      config: |
        #!/bin/bash
        # Install salt master
        set -ex
        logdir=/var/log/heat-deployments
        prefix=${logdir}/test-stack-log
        mkdir -p $logdir
        exec &> >(tee -a ${prefix}.log)
        [ -e ${prefix}.ran ] && exit 0

        echo "This is a test heat template"

  # Software deployment for salt-master. Deploys the salt-master softrware
  # configuration.
  # Also lists the git repos necessary to make the drupal stack work.
  deploy-salt-master:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: config-salt-master
      server:
        get_resource: master

  master:
    type: OS::Nova::Server
    properties:
      key_name:
        get_param: keyname
      image:
        get_param: image
      flavor:
        get_param: flavor
            # Get access from the master-port
      networks:
        - network: test-network
      config_drive: True

      # Using SoftwareConfigs - This needs to be set to SOFTWARE_CONFIG
      user_data_format: SOFTWARE_CONFIG
```
##### How can we verify your issue is addressed?
I don't understand the question? To verify it's addressed just ping whomever is assigned to this bug?

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
Run:
```
ansible neutron_agent -m command -a '/sbin/iptables -t mangle -A POSTROUTING -p tcp --sport 8000 -j CHECKSUM --checksum-fill'
```

##### What is your evaluation on the importance of this issue, and why?
Low. It doesn't affect anyone but the devs who might be working on heat stuff with an AIO.
###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] liberty-12.2
- [x] liberty-12.1

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Tasks:

- [ ] Reproduce the issue.
- [ ] Create a PR for fix and/or docs.
- [ ] Incorporate feedback from pull request reviews.
- [ ]  What is the gating for this on DEV and/or QE? Add related gating if appropriate. Also make sure current gating passes with this fix.. 
- [ ] Reach out to reporter (@rydor) to determine if the fix is resolving the issue.
- [ ] What are the upgrade impacts (if any).

**Comment by alextricity25** [comment]
Just saw:
https://review.openstack.org/#/c/330405/

Probably something to have in mind once RPC is pointing to the OSA stable/mitaka branch(assuming the PS above merges in time).

For now, I'll just make the change in the deploy script.

**Comment by b3rnard0** [comment]
@alextricity25 We prob want to triage this issue at next week's bug triage before we do too much work on this one given all that is being requested.

**Comment by odyssey4me** [comment]
@alextricity25 run-playbooks is meant to take care of the AIO need for the checksum rule. See https://github.com/openstack/openstack-ansible/blob/liberty/scripts/run-playbooks.sh#L103-L112

As you've pointed out this method has been changed in the master branch, see: https://review.openstack.org/326396 & https://review.openstack.org/327262

Due to continued problems relating to the method previously used, I've proposed the same changes to the stable/mitaka branch, see: https://review.openstack.org/330405 & https://review.openstack.org/330389

Note that this *only* affects the AIO due to the way the networking is configured. If you're running an AIO and you use run-playbooks more than once then you will have many more issues due to the lxcbr0 restart - it will cause all containers to lose connectivity.

**Comment by alextricity25** [comment]
@odyssey4me  Thanks for the info, Jesse :). Maybe it would be better to wait on the PR for this one until the PS in OSA stable/mitaka merges and RPC-O is pointing to OSA mitaka.

**Comment by hughsaunders** [comment]
Added to rcbops/u-suk-dev#96

**Comment by alextricity25** [comment]
blocked until https://review.openstack.org/330405 & https://review.openstack.org/330389 merge

**Comment by alextricity25** [comment]
Actually..we can go ahead and merge the PR for this into our mitaka branch. Once RPC-O points to the updated Mitaka SHA, we'll have to look into removing the iptables CHECKSUM fixes from the deploy.sh file and utilize the changes made in the OSA neutron role
