### ISSUE TITLE
Failures starting mysql on automatic Kilo to Liberty upgrades

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#1201]
##### What version (commit) do you encounter this issue on?
Upgrades from 11.1.9, 11.1.10, 11.1.11 to 12.1 or 12.2 branches
##### What type of issue is this (bug, feature, documentation, regression)?
bug
##### What is the expected behavior?
When galera_server role (Liberty version) is run on an existing deployment as part of a Kilo to Liberty upgrade it should be able to successfully restart the mysql service as part of applying any changes.
##### What is actually happening?
The test upgrade jobs are intermittently timing out.
The [console log](http://jenkins.propter.net/job/RPC-AIO/8001/console) from one of these jobs has the following
```
00:31:08 TASK: [galera_server | Start MySQL] ******************************************* 
00:51:08 Build timed out (after 20 minutes). Marking the build as aborted.
00:51:08 Build was aborted
```

An extract from [galera_server_error.log](http://jenkins.propter.net/job/RPC-AIO/8001/artifact/archive/openstack/jrpcaioiad-249_galera_container-e18df3e1/galera_server_error.log) provides further insight
```
160626  0:31:11 [ERROR] WSREP: Address already in use
160626  0:31:11 [ERROR] WSREP: failed to open gcomm backend connection: 98: error while trying to listen 'tcp://0.0.0.0:4567?socket.non_blocking=1', asio error 'Address already in use': 98 (Address already in use)
	 at gcomm/src/asio_tcp.cpp:listen():777
160626  0:31:11 [ERROR] WSREP: gcs/src/gcs_core.cpp:gcs_core_open():208: Failed to open backend connection: -98 (Address already in use)
160626  0:31:11 [ERROR] WSREP: gcs/src/gcs.cpp:gcs_open():1379: Failed to open channel 'rpc_galera_cluster' at 'gcomm://172.29.239.31,172.29.238.255,172.29.238.253': -98 (Address already in use)
160626  0:31:11 [ERROR] WSREP: gcs connect failed: Address already in use
160626  0:31:11 [ERROR] WSREP: wsrep::connect(gcomm://172.29.239.31,172.29.238.255,172.29.238.253) failed: 7
160626  0:31:11 [ERROR] Aborting
```

To see the latest failures reported by jenkins go to the [build summary page](http://jenkins.propter.net:443/#) and search for "Build Timeout: Install galera server / galera_server / Start MySQL".
##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
This is being encountered in the checks that are done automatically on pull requests and periodically.
##### How can we reproduce this issue?
The issue appears to happen intermittently and so seems to happen regularly when upgrading from Kilo to Liberty using our testing.
##### How can we verify your issue is addressed?
Once addressed the build summary page will no longer show failures due to this timeout.
##### What is your evaluation on the importance of this issue, and why?
prio-2, I'm not aware of this being seen in production but it does represent a potential issue.
###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [x] liberty-12.2

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

**Comment by mancdaz** [comment]
For anyone playing along, all my investigations and braindumps on what's going on can be found in https://github.com/rcbops/rpc-openstack/pull/1214

**Comment by git-harry** [comment]
There is an open OSA review to address this issue https://review.openstack.org/#/c/347195/

**Comment by b3rnard0** [comment]
@git-harry I'm going to remove the feature-gating label from this issue as it's not a feature.
