### ISSUE TITLE
tempest.scenario.test_server_basic_ops.TestServerBasicOps.test_server_basic_ops fails with PortNotFound

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#1211]
##### What version (commit) do you encounter this issue on?
master (when both Liberty and Mitaka) however it is more common since the move to Mitaka
##### What type of issue is this (bug, feature, documentation, regression)?
bug
##### What is the expected behavior?
Pull request and periodic jobs run to test the codebase. The final step of the job is to run tempest. These tempest tests should complete successfully.
##### What is actually happening?
The tempest test tempest.scenario.test_server_basic_ops.TestServerBasicOps.test_server_basic_ops fails.
```
07:58:09 ==============================
07:58:09 Failed 1 tests - output below:
07:58:09 ==============================
07:58:09 
07:58:09 tempest.scenario.test_server_basic_ops.TestServerBasicOps.test_server_basic_ops[compute,id-7fff3fb3-91d8-4fd0-bd7d-0204f1f180ba,network,smoke]
```

An extract of tempest's debugging information for [one of these failures](http://jenkins.propter.net/job/RPC-AIO/8244/consoleFull) is
```
07:58:09 Captured traceback:
07:58:09 ~~~~~~~~~~~~~~~~~~~
07:58:09     Traceback (most recent call last):
07:58:09       File "/opt/tempest_c2c90574a78c7704f06e8fac279c4f1d11365993/tempest/scenario/manager.py", line 108, in delete_wrapper
07:58:09         delete_thing(*args, **kwargs)
07:58:09       File "/opt/tempest_c2c90574a78c7704f06e8fac279c4f1d11365993/tempest/lib/services/compute/floating_ips_client.py", line 62, in delete_floating_ip
07:58:09         resp, body = self.delete(url)
07:58:09       File "/opt/tempest_c2c90574a78c7704f06e8fac279c4f1d11365993/tempest/lib/common/rest_client.py", line 290, in delete
07:58:09         return self.request('DELETE', url, extra_headers, headers, body)
07:58:09       File "/opt/tempest_c2c90574a78c7704f06e8fac279c4f1d11365993/tempest/lib/services/compute/base_compute_client.py", line 53, in request
07:58:09         method, url, extra_headers, headers, body)
07:58:09       File "/opt/tempest_c2c90574a78c7704f06e8fac279c4f1d11365993/tempest/lib/common/rest_client.py", line 645, in request
07:58:09         resp, resp_body)
07:58:09       File "/opt/tempest_c2c90574a78c7704f06e8fac279c4f1d11365993/tempest/lib/common/rest_client.py", line 764, in _error_checker
07:58:09         message=message)
07:58:09     tempest.lib.exceptions.ServerFault: Got server fault
07:58:09     Details: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
07:58:09     <class 'neutronclient.common.exceptions.PortNotFoundClient'>
```
##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
These occurences have been found during pull request and periodic testing. The have happened when Tempest is run at the end of the build.
##### How can we reproduce this issue?
I am unaware of specific steps, this failure is intermittent.
##### How can we verify your issue is addressed?
The [build summary](http://jenkins.propter.net:443/#) should no longer report failures due to this issue.
##### What is your evaluation on the importance of this issue, and why?
This slows the merger of new code, it may be specific to dev testing but should be considered a prio-2
###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] liberty-12.2

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

**Comment by mancdaz** [comment]
Here is the actual tempest failure output, isolated to just the specific failing tests:

http://paste.openstack.org/show/525933/

Here appears to be a launchpad bug filed against tempest for this issue:

https://bugs.launchpad.net/tempest/+bug/1586931

And here is the current fix proposed to tempest master (submitted 2016-07-02):

https://review.openstack.org/#/c/336842/

**Comment by mancdaz** [comment]
Yay - problem has been fixed upstream in master/mitaka/liberty

master: https://review.openstack.org/#/c/336842/
mitaka: https://review.openstack.org/#/c/338184/
liberty: https://review.openstack.org/#/c/338200/

@git-harry @hughsaunders we just need to track when OSA includes this in their sha bumps, and then ensure we include those sha bumps in our sha bump at some point :)

**Comment by hughsaunders** [comment]
While the neutron side of this issue has been fixed, the problem has now been pushed to nova. 

Excerpt from a recent [nova api log](http://jenkins.propter.net/job/JJB-RPC-AIO_master-swift/90/artifact/archive/openstack/jrpcaioiad-f0f_nova_api_os_compute_container-bf35e757/nova-api-os-compute.log/*view*/):

```
2016-08-24 16:57:38.196 2188 DEBUG keystoneauth.session [req-eac3c216-7480-4d5f-966d-50b5975916a7 6d871cbec69e4eff897e4f05081a9128 d3d34c3e228740b8bb2f8e99b815393c - - -] REQ: curl -g -i -X GET http://172.29.236.100:9696/v2.0/ports/67f35c46-6417-45ef-9c9a-de3d568efb5f.json -H "User-Agent: python-neutronclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}98a9246aab1074c66b7ca536523302ecb79f3037" _http_log_request /openstack/venvs/nova-13.3.1/lib/python2.7/site-packages/keystoneauth1/session.py:248
2016-08-24 16:57:38.688 2188 DEBUG keystoneauth.session [req-eac3c216-7480-4d5f-966d-50b5975916a7 6d871cbec69e4eff897e4f05081a9128 d3d34c3e228740b8bb2f8e99b815393c - - -] RESP: [404] Date: Wed, 24 Aug 2016 16:57:38 GMT Content-Length: 132 Content-Type: application/json; charset=UTF-8 X-Openstack-Request-Id: req-6a704a7c-92c1-454f-baf4-3b5bf77b4814 
RESP BODY: {"NeutronError": {"message": "Port 67f35c46-6417-45ef-9c9a-de3d568efb5f could not be found.", "type": "PortNotFound", "detail": ""}}
 _http_log_response /openstack/venvs/nova-13.3.1/lib/python2.7/site-packages/keystoneauth1/session.py:277
2016-08-24 16:57:38.689 2188 DEBUG neutronclient.v2_0.client [req-eac3c216-7480-4d5f-966d-50b5975916a7 6d871cbec69e4eff897e4f05081a9128 d3d34c3e228740b8bb2f8e99b815393c - - -] Error message: {"NeutronError": {"message": "Port 67f35c46-6417-45ef-9c9a-de3d568efb5f could not be found.", "type": "PortNotFound", "detail": ""}} _handle_fault_response /openstack/venvs/nova-13.3.1/lib/python2.7/site-packages/neutronclient/v2_0/client.py:263
2016-08-24 16:57:38.691 2188 ERROR nova.api.openstack.extensions [req-eac3c216-7480-4d5f-966d-50b5975916a7 6d871cbec69e4eff897e4f05081a9128 d3d34c3e228740b8bb2f8e99b815393c - - -] Unexpected exception in API method
2016-08-24 16:57:38.691 2188 ERROR nova.api.openstack.extensions Traceback (most recent call last):
2016-08-24 16:57:38.691 2188 ERROR nova.api.openstack.extensions   File "/openstack/venvs/nova-13.3.1/lib/python2.7/site-packages/nova/api/openstack/extensions.py", line 478, in wrapped
2016-08-24 16:57:38.691 2188 ERROR nova.api.openstack.extensions     return f(*args, **kwargs)
2016-08-24 16:57:38.691 2188 ERROR nova.api.openstack.extensions   File "/openstack/venvs/nova-13.3.1/lib/python2.7/site-packages/nova/api/openstack/compute/floating_ips.py", line 170, in delete
2016-08-24 16:57:38.691 2188 ERROR nova.api.openstack.extensions     instance = get_instance_by_floating_ip_addr(self, context, address)
2016-08-24 16:57:38.691 2188 ERROR nova.api.openstack.extensions   File "/openstack/venvs/nova-13.3.1/lib/python2.7/site-packages/nova/api/openstack/compute/floating_ips.py", line 67, in get_instance_by_floating_ip_addr
2016-08-24 16:57:38.691 2188 ERROR nova.api.openstack.extensions     context, address)
2016-08-24 16:57:38.691 2188 ERROR nova.api.openstack.extensions   File "/openstack/venvs/nova-13.3.1/lib/python2.7/site-packages/nova/network/neutronv2/api.py", line 1424, in get_instance_id_by_floating_address
2016-08-24 16:57:38.691 2188 ERROR nova.api.openstack.extensions     port = self._show_port(context, fip['port_id'], neutron_client=client)
2016-08-24 16:57:38.691 2188 ERROR nova.api.openstack.extensions   File "/openstack/venvs/nova-13.3.1/lib/python2.7/site-packages/nova/network/neutronv2/api.py", line 896, in _show_port
2016-08-24 16:57:38.691 2188 ERROR nova.api.openstack.extensions     raise exception.PortNotFound(port_id=port_id)
2016-08-24 16:57:38.691 2188 ERROR nova.api.openstack.extensions PortNotFound: Port id 67f35c46-6417-45ef-9c9a-de3d568efb5f could not be found.
2016-08-24 16:57:38.691 2188 ERROR nova.api.openstack.extensions 
2016-08-24 16:57:38.710 2188 INFO nova.api.openstack.wsgi [req-eac3c216-7480-4d5f-966d-50b5975916a7 6d871cbec69e4eff897e4f05081a9128 d3d34c3e228740b8bb2f8e99b815393c - - -] HTTP exception thrown: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
<class 'nova.exception.PortNotFound'>
```

Bug [1586931](https://bugs.launchpad.net/tempest/+bug/1586931) Has been fixed in Nova but backport to liberty is still pending.

**Comment by git-harry** [comment]
@hughsaunders would you mind putting this in a new bug instead of reopening this one, it throws off all the reporting and makes work harder to track.
