### ISSUE TITLE
OSA [1588051] Implement better options for handling log sizes via logrotate

### ISSUE THREAD

**Issue by ameserole** [rcbops/rpc-openstack#1291]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
Second band-aid suggested 
https://bugs.launchpad.net/openstack-ansible/+bug/1588051
##### What is actually happening?
Second band-aid suggested 
https://bugs.launchpad.net/openstack-ansible/+bug/1588051
##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Second band-aid suggested 
https://bugs.launchpad.net/openstack-ansible/+bug/1588051
##### How can we reproduce this issue?
Second band-aid suggested 
https://bugs.launchpad.net/openstack-ansible/+bug/1588051
##### How can we verify your issue is addressed?
Second band-aid suggested 
https://bugs.launchpad.net/openstack-ansible/+bug/1588051
##### If you are using or know of a workaround please describe the necessary steps?
Second band-aid suggested 
https://bugs.launchpad.net/openstack-ansible/+bug/1588051
##### What is your evaluation on the importance of this issue, and why?
Second band-aid suggested 
https://bugs.launchpad.net/openstack-ansible/+bug/1588051

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by ameserole** [comment]
Looks like this one already got addressed as well but the patch was never linked to the bug report in OSA
