### ISSUE TITLE
OpenStack logs are duplicated to /var/log/upstart

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#1311]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
master

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
OpenStack logs are not duplicated in /var/log/upstart

##### What is actually happening?
OpenStack service logs are logged both in the appropriate service log files and in /var/log/upstart

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
This was discovered while was being done to update ELK for Mitaka. This was originally being tracked by https://github.com/rcbops/u-suk-dev/issues/271

##### How can we reproduce this issue?
Deploy master and check /var/log/upstart for OpenStack service logs then see if those logs also exist in separate OpenStack service log files.

##### How can we verify your issue is addressed?
/var/log/upstart is free of OpenStack service logs.

##### What is your evaluation on the importance of this issue, and why?
The has the potential to cause disk space issues, but does not block any releases.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master https://github.com/rcbops/rpc-openstack/pull/1352
- [x] mitaka-13.0 https://github.com/rcbops/rpc-openstack/pull/1373
- [x] liberty-12.2 https://github.com/rcbops/rpc-openstack/pull/1321

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):
