### ISSUE TITLE
Mitaka galera log bind mount is wrong

### ISSUE THREAD

**Issue by evrardjp** [rcbops/rpc-openstack#1326]
#### This section is completed by the issue reporter
master

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

See more details here: https://bugs.launchpad.net/openstack-ansible/+bug/1609862

##### What is actually happening?

See more details here: https://bugs.launchpad.net/openstack-ansible/+bug/1609862

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

See more details here: https://bugs.launchpad.net/openstack-ansible/+bug/1609862

##### How can we reproduce this issue?

See more details here: https://bugs.launchpad.net/openstack-ansible/+bug/1609862

##### How can we verify your issue is addressed?

Check logs are properly bind mounted on the hosts: we shouldn't have no logs in the folder

##### What is your evaluation on the importance of this issue, and why?

This requires a galera container restart and it's therefore painful. So, probably high.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master https://github.com/rcbops/rpc-openstack/pull/1373
- [x] mitaka-13.0 https://github.com/rcbops/rpc-openstack/pull/1373

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by evrardjp** [comment]
This could affect any minor update change, so it's better to do it as soon as possible, before any official release.

**Comment by major** [comment]
Working on a WIP patch.

**Comment by major** [comment]
Fix proposed to OSA's `stable/mitaka` branch:

* https://review.openstack.org/358852

Reviews needed!

**Comment by major** [comment]
Merged in OSA: https://review.openstack.org/#/c/358852/

SHA bump needed for RPC.

**Comment by git-harry** [comment]
@major issues need to have the appropriate swimlane label when approved so that they are being correctly tracked.

/cc @b3rnard0

**Comment by major** [comment]
Ah I missed that one. Thanks for adding it.
