### ISSUE TITLE
 Playbook Runs Fail in Multi-Domain Environments 

### ISSUE THREAD

**Issue by brainerd123** [rcbops/rpc-openstack#1334]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
master

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
playbook runs complete

##### What is actually happening?
This is an OSA bug and can be found here:  https://bugs.launchpad.net/openstack-ansible/+bug/1614211 

Playbook runs for any of the OpenStack services fail in Mitaka environments with multiple domains and the Keystone v3 sample policy in place found here:
https://github.com/openstack/keystone/blob/stable/mitaka/etc/policy.v3cloudsample.json

More details are in the bug...

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
see OSA bug link

##### How can we reproduce this issue?
see OSA bug link

##### How can we verify your issue is addressed?
see OSA bug link

##### If you are using or know of a workaround please describe the necessary steps?
see OSA bug link

##### What is your evaluation on the importance of this issue, and why?
see OSA bug link

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

OSA 13.1.5

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by nrb** [comment]
https://review.openstack.org/#/c/356711/ is the backport for the keystone library code to support domain-level scoping. There will also need to be a patch to the keystone role to use it, though I've not checked to see if one is in OSA master yet

**Comment by nrb** [comment]
@seancarlisle I've posted some further questions on the upstream bug. Ideally, if I could get a copy of the keystone overrides you're providing in `user_variables.yml` I can do more accurate testing. It's possible there's an issue with the tempating plugin we use that's causing a conflicting policy.

**Comment by git-harry** [comment]
@nrb would you mind providing a summary of what has happened upstream. I'm not clear as to whether or not this has been fixed.

**Comment by nrb** [comment]
Sure, sorry about not updating this further.

For the specific install, the problem was worked around via modified policy configuration, so for the particular customer, it's more or less done, though there are some discrepancies between how Keystone and Horizon handle the policy that makes it a support burden.

In terms of fixing the bug, during Ocata we'll be looking at replacing OSA's included modules with upstream Ansible ones that are developed by the OpenStack Infra team. 

I've left the bug open upstream because there is ongoing work to address it, but in terms of the affected RPC customer this appears to have at least been mitigated, so I think this bug can be closed.

**Comment by git-harry** [comment]
@brainerd123 @rcbops/support-feedback do you agree with Nolan's comments that this can be closed?

**Comment by brainerd123** [comment]
Hello,

Correct, this can be closed as per Nolan's comments.

best,
AB
