### ISSUE TITLE
Add OPENSTACK_KEYSTONE_ADMIN_ROLES to horizon_local_settings.py.j2 Template

### ISSUE THREAD

**Issue by brainerd123** [rcbops/rpc-openstack#1335]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
master

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
see OSA bug 
##### What is actually happening?
At present, the horizon_local_settings.py.j2 template file does not have the OPENSTACK_KEYSTONE_ADMIN_ROLES option present and thusly it is not configurable. This option is necessary when an environment has more than one administrative role (such as admin and cloud-admin) due to RBAC policy overrides. While the option doesn't exist in the default file provided by the source, documentation exists for this option: https://github.com/openstack/horizon/blob/eaa194e4978e60ea713a73775a58f0188cfc5b59/doc/source/topics/settings.rst#openstack_keystone_admin_roles 

This is an OSA: https://bugs.launchpad.net/openstack-ansible/+bug/1614213 

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
see OSA bug 
##### How can we reproduce this issue?
see OSA bug 
##### How can we verify your issue is addressed?
see OSA bug 
##### If you are using or know of a workaround please describe the necessary steps?
see OSA bug 
##### What is your evaluation on the importance of this issue, and why?
see OSA bug 

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master https://github.com/rcbops/rpc-openstack/pull/1370
- [x] mitaka-13.0 https://github.com/rcbops/rpc-openstack/pull/1373

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by nrb** [comment]
https://review.openstack.org/#/c/356727/ is the master review, though it will require a backport to stable/mitaka once accepted.

**Comment by major** [comment]
Backport pending to stable/mitaka:

* https://review.openstack.org/#/c/358805/

**Comment by major** [comment]
The backport just merged into OSA's stable/mitaka branch.
