### ISSUE TITLE
Cinder volume services not starting

### ISSUE THREAD

**Issue by jpmontez** [rcbops/rpc-openstack#1394]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

```
root@627551-infra01:/opt/rpc-openstack# git describe --all
r13.0.0rc2
```

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
For Cinder volumes services to start successfully and for Cinder actions to complete successfully.

##### What is actually happening?
The Cinder volume services are failing to start after a deployment of r13.0.0rc2. This is causing all Cinder actions to fail.

```
root@627551-infra01-utility-container-aebe9553:~# cinder create --name test 1
+--------------------------------+--------------------------------------+
|            Property            |                Value                 |
+--------------------------------+--------------------------------------+
|          attachments           |                  []                  |
|       availability_zone        |                 nova                 |
|            bootable            |                false                 |
|      consistencygroup_id       |                 None                 |
|           created_at           |      2016-09-07T15:33:16.000000      |
|          description           |                 None                 |
|           encrypted            |                False                 |
|               id               | 220621f4-99e2-437e-8d0d-2eef035c8c30 |
|            metadata            |                  {}                  |
|        migration_status        |                 None                 |
|          multiattach           |                False                 |
|              name              |                 test                 |
|     os-vol-host-attr:host      |                 None                 |
| os-vol-mig-status-attr:migstat |                 None                 |
| os-vol-mig-status-attr:name_id |                 None                 |
|  os-vol-tenant-attr:tenant_id  |   e6c727d3b48f4c4d8012a5a9a95e3705   |
|       replication_status       |               disabled               |
|              size              |                  1                   |
|          snapshot_id           |                 None                 |
|          source_volid          |                 None                 |
|             status             |               creating               |
|           updated_at           |                 None                 |
|            user_id             |   90552827bf614789b0a1b28252a80df4   |
|          volume_type           |                 None                 |
+--------------------------------+--------------------------------------+
```

```
root@627551-infra01-utility-container-aebe9553:~# cinder show 220621f4-99e2-437e-8d0d-2eef035c8c30
+--------------------------------+--------------------------------------+
|            Property            |                Value                 |
+--------------------------------+--------------------------------------+
|          attachments           |                  []                  |
|       availability_zone        |                 nova                 |
|            bootable            |                false                 |
|      consistencygroup_id       |                 None                 |
|           created_at           |      2016-09-07T15:33:16.000000      |
|          description           |                 None                 |
|           encrypted            |                False                 |
|               id               | 220621f4-99e2-437e-8d0d-2eef035c8c30 |
|            metadata            |                  {}                  |
|        migration_status        |                 None                 |
|          multiattach           |                False                 |
|              name              |                 test                 |
|     os-vol-host-attr:host      |                 None                 |
| os-vol-mig-status-attr:migstat |                 None                 |
| os-vol-mig-status-attr:name_id |                 None                 |
|  os-vol-tenant-attr:tenant_id  |   e6c727d3b48f4c4d8012a5a9a95e3705   |
|       replication_status       |               disabled               |
|              size              |                  1                   |
|          snapshot_id           |                 None                 |
|          source_volid          |                 None                 |
|             status             |                error                 |
|           updated_at           |      2016-09-07T15:33:16.000000      |
|            user_id             |   90552827bf614789b0a1b28252a80df4   |
|          volume_type           |                 None                 |
+--------------------------------+--------------------------------------+
```

```
2016-09-08 01:29:24.836 19106 INFO cinder.rpc [req-81ece211-20ae-467e-b097-15c1da256c51 - - - - -] Automatically selected cinder-scheduler objects version 1.3 as minimum service version.
2016-09-08 01:29:24.842 19106 INFO cinder.rpc [req-81ece211-20ae-467e-b097-15c1da256c51 - - - - -] Automatically selected cinder-scheduler RPC version 2.0 as minimum service version.
2016-09-08 01:29:24.889 19106 INFO cinder.volume.manager [req-81ece211-20ae-467e-b097-15c1da256c51 - - - - -] Determined volume DB was not empty at startup.
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume [req-81ece211-20ae-467e-b097-15c1da256c51 - - - - -] Volume service 627559-storage01.syd2.rpc.rackspace.com@lvm failed to start.
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume Traceback (most recent call last):
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume   File "/openstack/venvs/cinder-13.3.3/lib/python2.7/site-packages/cinder/cmd/volume.py", line 81, in main
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume     binary='cinder-volume')
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume   File "/openstack/venvs/cinder-13.3.3/lib/python2.7/site-packages/cinder/service.py", line 268, in create
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume     service_name=service_name)
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume   File "/openstack/venvs/cinder-13.3.3/lib/python2.7/site-packages/cinder/service.py", line 150, in __init__
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume     *args, **kwargs)
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume   File "/openstack/venvs/cinder-13.3.3/lib/python2.7/site-packages/cinder/volume/manager.py", line 284, in __init__
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume     active_backend_id=curr_active_backend_id)
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume   File "/openstack/venvs/cinder-13.3.3/lib/python2.7/site-packages/oslo_utils/importutils.py", line 44, in import_object
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume   File "/openstack/venvs/cinder-13.3.3/lib/python2.7/site-packages/oslo_utils/importutils.py", line 36, in import_class
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume     traceback.format_exception(*sys.exc_info())))
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume ImportError: Class LVMISCSIDriver cannot be found (['Traceback (most recent call last):\n', '  File "/openstack/venvs/cinder-13.3.3/lib/python2.7/site-packages/oslo_utils/importutils.py", line 32, in import_class\n    return getattr(sys.modules[mod_str], class_str)\n', "AttributeError: 'module' object has no attribute 'LVMISCSIDriver'\n"])
2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume
2016-09-08 01:29:24.916 19106 ERROR cinder.cmd.volume [req-81ece211-20ae-467e-b097-15c1da256c51 - - - - -] No volume service(s) started successfully, terminating.
```

See one example test result [here](http://jenkins.openstack-ansible.com/job/RPC-OA/251/testReport/tempest.api.volume.test_volumes_get/VolumesV1GetTest/test_volume_create_get_update_delete_id_27fb0e9f_fb64_41dd_8bdb_1ffa762f0d51_smoke_/).

##### What were you attempting to do when you encountered this error (give as much detail as possible)?

Deploying r13.0.0rc2 and running Tempest immediately after a successful playbook run.

##### How can we reproduce this issue?

Run a r13.0.0rc2 deployment in the FCFS-SYD2-LAB01 laboratory in LEM.

##### How can we verify your issue is addressed?

By running the Cinder sub-section of Tempest API tests or by manually creating a Cinder volume.

##### If you are using or know of a workaround please describe the necessary steps?

N/A

##### What is your evaluation on the importance of this issue, and why?

It's very important because Cinder is a core feature of the product.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by weezer** [comment]
i got the same error on SAT6

oslo_utils/importutils.py", line 36, in import_class
2016-09-07 15:56:01.897 363 ERROR cinder.cmd.volume     traceback.format_exception(*sys.exc_info())))
2016-09-07 15:56:01.897 363 ERROR cinder.cmd.volume ImportError: Class LVMISCSIDriver cannot be found (['Traceback (most recent call last):\n', '  File "/openstack/venvs/cinder-13.3.3/lib/python2.7/sitepackages/oslo_utils/importutils.py"
, line 32, in import_class\n    return getattr(sys.modules[mod_str], class_str)\n', "AttributeError: 'module' object has no attribute 'LVMISCSIDriver'\n"])
2016-09-07 15:56:01.897 363 ERROR cinder.cmd.volume


-------------------------------------
tempest result

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/opt/tempest_untagged/tempest/test.py", line 112, in wrapper
        return f(self, *func_args, **func_kwargs)
      File "/opt/tempest_untagged/tempest/scenario/test_minimum_basic.py", line 112, in test_minimum_basic_scenario
        volume = self.create_volume()
      File "/opt/tempest_untagged/tempest/scenario/manager.py", line 286, in create_volume
        volume['id'], 'available')
      File "/opt/tempest_untagged/tempest/common/waiters.py", line 174, in wait_for_volume_status
        raise exceptions.VolumeBuildErrorException(volume_id=volume_id)
    tempest.exceptions.VolumeBuildErrorException: Volume e07fac6d-4ded-46f4-8e4a-393cf8341d7e failed to build and is i
n ERROR status

**Comment by sigmavirus24** [comment]
Can you share the cinder config for this? 

> 2016-09-08 01:29:24.915 19106 ERROR cinder.cmd.volume ImportError: Class LVMISCSIDriver cannot be found (['Traceback (most recent call last):\n', '  File "/openstack/venvs/cinder-13.3.3/lib/python2.7/site-packages/oslo_utils/importutils.py", line 32, in import_class\n    return getattr(sys.modules[mod_str], class_str)\n', "AttributeError: 'module' object has no attribute 'LVMISCSIDriver'\n"])

Makes me think this is a configuration problem, potentially

**Comment by jpmontez** [comment]
@sigmavirus24 The cinder config is as follows:

```
# Ansible managed: /etc/ansible/roles/os_cinder/templates/cinder.conf.j2 modified on 2016-08-14 20:28:48 by root on 627551-infra01.XXX


[DEFAULT]
verbose = True
# Disable stderr logging
use_stderr = False
debug = False
fatal_deprecations = False
my_ip = 10.240.0.199

osapi_volume_workers = 12

rootwrap_config = /etc/cinder/rootwrap.conf
api_paste_config = /etc/cinder/api-paste.ini
auth_strategy = keystone

## Cinder API's enabled
enable_v1_api = True
enable_v2_api = True


## RabbitMQ
rpc_backend = rabbit

## Quota
quota_volumes = 10
quota_snapshots = 10
quota_consistencygroups = 10
quota_gigabytes = 1000
quota_backups = 10
quota_backup_gigabytes = 1000

## Nova
nova_catalog_info = compute:nova:internalURL
nova_catalog_admin_info = compute:nova:adminURL

## Glance
# TODO(odyssey4me): Remove this conditional once https://review.openstack.org/299928 has merged
glance_api_servers = 172.20.136.10:9292
glance_num_retries = 0
glance_api_version = 1

volume_clear = shred
volume_clear_size = 0
volume_clear_ionice = -c3
volume_name_template = volume-%s

storage_availability_zone = nova
default_availability_zone = nova

iscsi_helper = tgtadm
iscsi_iotype = fileio
iscsi_ip_address = 127.0.0.1
iscsi_num_targets = 100
iscsi_port = 3260

client_socket_timeout = 900


enabled_backends=lvm

# All given backend(s)
[lvm]
volume_driver=cinder.volume.drivers.lvm.LVMISCSIDriver
volume_backend_name=LVM_iSCSI
volume_group=cinder-volumes


[database]
connection = mysql+pymysql://cinder:XXX@172.20.136.10/cinder?charset=utf8

[oslo_messaging_rabbit]
rabbit_port = 5671
rabbit_userid = cinder
rabbit_password = XXX
rabbit_virtual_host = /cinder
rabbit_hosts = 172.20.137.227:5671,172.20.139.183:5671,172.20.136.225:5671
rabbit_use_ssl = True

[oslo_concurrency]
lock_path = /var/lock/cinder

[profiler]
profiler_enabled = False
trace_sqlalchemy = False

[keymgr]
encryption_auth_url = http://172.20.136.10:5000/v3

[keystone_authtoken]
insecure = False
auth_plugin = password
signing_dir = /var/cache/cinder
auth_url = http://172.20.136.10:35357/v3
auth_uri = http://172.20.136.10:5000
project_domain_id = default
user_domain_id = default
project_name = service
username = cinder
password = XXX

memcached_servers = 172.20.138.41:11211,172.20.139.205:11211,172.20.137.241:11211

token_cache_time = 300
revocation_cache_time = 60

# if your memcached server is shared, use these settings to avoid cache poisoning
memcache_security_strategy = ENCRYPT
memcache_secret_key = XXX

# if your keystone deployment uses PKI, and you value security over performance:
check_revocations_for_cached = False
```

_Note: The passwords/secrets have been removed._

**Comment by sigmavirus24** [comment]
So `LVMISCSIDriver` has been removed but `LVMVolumeDriver` is what actually exists.

**Comment by BjoernT** [comment]
My test volume created. Seems like we need to highlight this change in the release notes, especially for upgrades

**Comment by sigmavirus24** [comment]
@BjoernT I was just going to create a documentation bug to highlight this as a pre-flight check

**Comment by alextricity25** [comment]
How did VLMISCSIDriver get in there? The sample config in liberty onwards have LVMVolumeDriver set for the cinder driver: https://github.com/openstack/openstack-ansible/blob/liberty/etc/openstack_deploy/openstack_user_config.yml.example#L597
Using an older config, maybe?

**Comment by Apsu** [comment]
@alextricity25 Good call, even looking in eol/kilo the example has LVMVolumeDriver. Guessing the other has been deprecated a good long while and finally got axed. This must be some old config that got copypasta'd around forever. Woo!

**Comment by BjoernT** [comment]
That is just based on old installations where they used the LVMISCSI driver and the same configs have been reused in testing I guess

**Comment by jpmontez** [comment]
Updating the LVM driver name solved this. I think the only remaining item is highlighting this in the documentation.

**Comment by sigmavirus24** [comment]
@jpmontez that's what I asked for with https://github.com/rackerlabs/docs-rpc/issues/551 so I think that'll be taken care of appropriately.

**Comment by sigmavirus24** [comment]
@git-harry you've included release notes for this for r13.0 and r13.1... should the milestone be changed?

**Comment by git-harry** [comment]
This is noted in with docs and a release note is being added https://github.com/rcbops/u-suk-dev/issues/398
