### ISSUE TITLE
[OSA] Mitaka: libvirt-python package not consistently build in repo

### ISSUE THREAD

**Issue by claco** [rcbops/rpc-openstack#1432]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added
##### What is the expected behavior?

Linked in from upstream, via the deployments folks:  https://bugs.launchpad.net/openstack-ansible/+bug/1625859

I was installing OSA 13.3.3 on two different cluster and we noticed difference around libvirt-python inside the venv:

```
libvirt_python-1.3.2-cp27-none-linux_x86_64.whl -> /var/www/repo/pools/libvirt_python/libvirt_python-1.3.2-cp27-none-linux_x86_64.whl
```
##### What is actually happening?

```
libvirt_python-1.3.2-cp27-cp27mu-linux_x86_64.whl -> /var/www/repo/pools/libvirt_python/libvirt_python-1.3.2-cp27-cp27mu-linux_x86_64.whl
```

```
>>> import libvirtmod
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
 ImportError: /usr/lib/libvirt.so.0: version `LIBVIRT_1.2.16' not found (required by /openstack/venvs/nova-13.3.3/lib/python2.7/site-packages/libvirtmod.so)
```
##### What were you attempting to do when you encountered this error (give as much detail as possible)?

Install Mitaka 13.0.0
##### How can we reproduce this issue?

Install Mitaka 13.0.0
##### If you are using or know of a workaround please describe the necessary steps?

The issue was fixed after I just copied the libvirt_python-1.3.2-cp27-none-linux_x86_64.whl wheel from a working deployment and installed it.
Personally I don't know why we not just copying /usr/lib/python2.7/dist-packages/libvirtmod\* into the venv, that way we would make sure that the libvirt version and libvirt-python do match.

All the other libraries like libvirt/qemu where exactly the same so it is not known why the repo build process builds entirely different wheels even if all requirements.txt match
##### What is your evaluation on the importance of this issue, and why?

---
###### For each pull request, update the branch line to reference it.
- [x] master
- [x] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo
##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:
##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:
##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.
##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues)
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc)
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by git-harry** [comment]
Moved to 'status-pending-sha-update' because this has already been addressed upstream.

**Comment by alextricity25** [comment]
@git-harry: The bug description lists liberty-12.2 and kilo as affected branches, but upstream didn't backport anything for this fix. Do we still need to address this issue in our liberty-12.2 and kilo branches?

**Comment by git-harry** [comment]
@alextricity25 this issue lists all branches by default. Based on the upstream bug report I would assume Liberty and earlier are not affected which correlates with this having not been reported before. However, we should probably look to confirm that before we close this issue.

@odyssey4me can the [bug](https://bugs.launchpad.net/openstack-ansible/+bug/1625859) affect releases before Mitaka? Have we been lucky so far or is Mitaka when the bug was introduced?

**Comment by odyssey4me** [comment]
@git-harry The bug fix was preventative. The issue itself was not reproducable given the information provided, however based on experience with Newton and OpenStack-CI compiled wheels we did encounter an issue and resolved it this way.

The only way I see this affecting anything less than Newton is if there are mixed versions of the apt packages in play as outlined in the OSA bug. ie If the compute host and repo container (or wherever the wheel is compiled) have differing versions of the libvirt apt packages.

Liberty still has a tie to rpc-repo, so there may be an issue introduced there by package differences. It may therefore be important to do some sort of backport to Liberty.

In order to cover the possibility of differing OS release between the control plane and compute hosts there is a proposed patch in review: https://review.openstack.org/396821

It's a bit of a hack, but so far we don't see any alternatives. As the intent is for deployers to deploy Newton on Trusty, then switch to Newton on Xenial the intent is to backport that patch to Newton. Due to the possibility of mixed Ubuntu/CentOS environments going forward the intent is to keep it that way from Newton onwards.
