### ISSUE TITLE
13.1.0rc1 upgrades fail at bash scripts/deploy-rpc-playbooks.sh

### ISSUE THREAD

**Issue by Rydor** [rcbops/rpc-openstack#1433]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
r13.1.0rc1
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

The execution of  bash scripts/deploy-rpc-playbooks.sh from the upgrade instructions should successfully upgrade from Liberty 12.2.4 to Mitaka 13.1.0 with no errors occurring during the execution of playbook.
##### What is actually happening?
Receiving this error output:

bash scripts/deploy-rpc-playbooks.sh
+ set -o pipefail
+ source /opt/rpc-openstack/scripts/functions.sh
++ export ANSIBLE_PARAMETERS=
++ ANSIBLE_PARAMETERS=
++ export FORKS=24
++ FORKS=24
+ cd /opt/rpc-openstack/rpcd/playbooks/
+ run_ansible rpc-support.yml
+ openstack-ansible --forks 24 rpc-support.yml
Variable files: "-e @/etc/openstack_deploy/user_osa_secrets.yml -e @/etc/openstack_deploy/user_osa_variables_defaults.yml -e @/etc/openstack_deploy/user_osa_variables_overrides.yml -e @/etc/openstack_deploy/user_rpco_secrets.yml -e @/etc/openstack_deploy/user_rpco_variables_defaults.yml -e @/etc/openstack_deploy/user_rpco_variables_overrides.yml -e @/etc/openstack_deploy/user_secrets.yml "
ERROR: config_template is not a legal parameter in an Ansible task or handler

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Execution of an upgrade from liberty 12.2.4 to Mitaka 13.1.0

More specifically by following the upgrade instructions available through rpc-openstack/scripts/test-upgrade.sh line 124

##### How can we reproduce this issue?
Attempt to upgrade liberty 12.2.4 to Mitaka 13.1.0
##### How can we verify your issue is addressed?
There is no longer an Ansible error.
##### What is your evaluation on the importance of this issue, and why?

This is a blocker for QE as we can not perform upgrade testing until we are able to upgrade one of our lab environments. 
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
Hi, @Rydor. The problems seems to be that Ansible can't find the config_template module. Did you already update Ansible by running ``bootstrap-ansible.sh``?

**Comment by Rydor** [comment]
Yes, I was able to successfully execute bash scripts/bootstrap-ansible.sh. I also received "System is bootstrapped and ready for use." back from the script.

**Comment by alextricity25** [comment]
@Rydor, could you supply the output of these commands, please?
```
ls /etc/ansible/plugins/action
cat /opt/rpc-openstack/rpcd/playbooks/ansible.cfg
```

**Comment by Rydor** [comment]
ls /etc/ansible/plugins/action
ls: cannot access /etc/ansible/plugins/action: No such file or directory


cat /opt/rpc-openstack/rpcd/playbooks/ansible.cfg
[defaults]
gathering = smart
host_key_checking = False

# Setting forks should be based on your system. The Ansible defaults to 5,
# the os-lxc-hosts assumes that you have a system that can support
# OpenStack, thus it has been conservatively been set to 15
forks = 15

# SSH timeout
timeout = 120

# Set the path to the folder in openstack-ansible which holds the dynamic
# inventory script - new config setting for ansible v1.9 and above
inventory = ../../openstack-ansible/playbooks/inventory/

# TODO(evrardjp - Newton) This library folder will be moved in Newton to
# /etc/ansible/roles/plugins/ . This config change won't be needed anymore.
library = /etc/ansible/plugins/library

# Set the path to the folder in openstack-ansible which holds the roles
# that are depended on by the rpc-openstack roles
roles_path = ../../openstack-ansible/playbooks/roles/:/etc/ansible/roles/

# TODO(evrardjp - Newton) This lookup folder will be moved in Newton to
# /etc/ansible/roles/plugins/ . This config change won't be needed anymore.
lookup_plugins = /etc/ansible/plugins/lookup

# TODO(evrardjp - Newton) This filter folder will be moved in Newton to
# /etc/ansible/roles/plugins/ . This config change won't be needed anymore.
filter_plugins = /etc/ansible/plugins/filter

# TODO(evrardjp - Newton) This action folder will be moved in Newton to
# /etc/ansible/roles/plugins/ . This config change won't be needed anymore.
action_plugins = /etc/ansible/plugins/action

# TODO(evrardjp - Newton) This callback folder will be moved in Newton to
# /etc/ansible/roles/plugins/ . This config change won't be needed anymore.
callback_plugins = /etc/ansible/plugins/callback

[ssh_connection]
pipelining = True

**Comment by alextricity25** [comment]
Thanks @Rydor. It looks to me like you ran ``bootstrap-ansible.sh`` under maybe the liberty-12.2 branch, or maybe while still under the 12.X tag.
Could you re-run ``bootstrap-ansible.sh`` while under the 13.X tag, then report back with the output of that ``ls`` command? The /etc/ansible/plugins directory should be populated by ``boostrap-ansible.sh``.

**Comment by Rydor** [comment]
Thanks for the help troubleshooting this. I did not execute a proper git submodule init / sync/ update so the latest openstack-ansible didn't get pulled in. After updating submodules it was able to get through this issue. As a result we can close this issue. I am not sure if that is something i do or you do.
