### ISSUE TITLE
os_neutron ns-metadata-proxy cleanup error attempting to kill PID

### ISSUE THREAD

**Issue by Apsu** [rcbops/rpc-openstack#1437]
##### On which version(s) do you encounter this issue?
master upgrade from liberty-12.2

###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
liberty-12.2 to master

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

Upstream bug: https://bugs.launchpad.net/openstack-ansible/+bug/1627185

##### What is the expected behavior?
Old Neutron ns-metadata-proxy processes are successfully killed prior to restarting into the upgraded versions

##### What is actually happening?
Sometimes the PID from the pgrep/grep is either no longer there or the filtering malforms it so this happens:

```
13:35:48 failed: [jrpcaioiad-3a8_neutron_agents_container-101ec306] => {"changed": true, "cmd": "for ns_pid in $(pgrep neutron-ns-meta); do\n echo $(readlink -f \"/proc/$ns_pid/exe\") | grep -qv \"13.3.4\"\n if [ $? -eq 0 ]; then\n (echo \"old metadata proxy pid found running clean up on $ns_pid\"; kill -9 \"$ns_pid\")\n fi\n done", "delta": "0:00:00.049977", "end": "2016-09-23 13:35:48.950575", "rc": 1, "start": "2016-09-23 13:35:48.900598", "warnings": []}
13:35:48 stderr: /bin/sh: 4: kill: No such process
13:35:48
13:35:48 /bin/sh: 4: kill: No such process
13:35:48 stdout: old metadata proxy pid found running clean up on 1337
13:35:48 old metadata proxy pid found running clean up on 2781
```

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-upgrade this automatic gate job

##### How can we reproduce this issue?
Rerun the gate job a few times

##### How can we verify your issue is addressed?
Gate jobs don't fail from missing PIDs any more

##### If you are using or know of a workaround please describe the necessary steps?
Seems to be a race condition or process filtering oddity, not sure of a workaround without hand-modifying the Galaxy role

##### What is your evaluation on the importance of this issue, and why?
I was told this was high priority

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master https://github.com/rcbops/rpc-openstack/pull/1454
- [x] mitaka-13.1 https://github.com/rcbops/rpc-openstack/pull/1455
- [x] mitaka-13.0 https://github.com/rcbops/rpc-openstack/pull/1469

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [x] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by Apsu** [comment]
Connects rcbops/u-suk-dev#371

**Comment by git-harry** [comment]
@Apsu @hughsaunders I had a look at the build summary page for upgrade failures related to this issue and couldn't find any. Are you able to quantify how frequently this failure is seen? From what I can see this is an infrequent race condition and so shouldn't block the release of r13.1.0 and so I think it should be a prio-2 but will leave the priority undecided until we have more information in the issue.

**Comment by evrardjp** [comment]
https://review.openstack.org/#/c/378535/ is on its way to mitaka.

**Comment by Apsu** [comment]
Go Jenkins go!

**Comment by git-harry** [comment]
@Apsu does this need backporting to Liberty upstream and here?

**Comment by Apsu** [comment]
@git-harry No it does not. The handler https://github.com/openstack/openstack-ansible/blob/liberty/playbooks/roles/os_neutron/handlers/main.yml does not include the old proxy killing logic, and I can't find any similar logic of any kind looking in the entire os_neutron role for Liberty.
