### ISSUE TITLE
L>M Upgrade: OSA Bug 1632098: stale RabbitMQ queues

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1483]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

r13.1.0rc1
13.3.4-1-ga489036
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added
##### What is the expected behavior?

No stale queues are present after mitaka upgrade
##### What is actually happening?

See https://bugs.launchpad.net/openstack-ansible/+bug/1632098
##### What were you attempting to do when you encountered this error (give as much detail as possible)?

See https://bugs.launchpad.net/openstack-ansible/+bug/1632098
##### How can we reproduce this issue?

Just upgrade from Liberty to Mitaka
##### How can we verify your issue is addressed?

No rabbit queues are present after the mitaka upgrade
##### If you are using or know of a workaround please describe the necessary steps?

Manually deleted all queues without any consumer through rabbitmq admin
##### What is your evaluation on the importance of this issue, and why?

Prio 1 since this issue will kill rabbitmq service over time

---
###### For each pull request, update the branch line to reference it.
- [x] master
- [x] mitaka-13.1
##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [x] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:
##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:
##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.
##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues)
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc)
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by evrardjp** [comment]
End of day update:
https://review.openstack.org/#/c/389795/

**Comment by b3rnard0** [comment]
@evrardjp Will you be working on this at the Summit? Just curious b/c of the prio-1 nature of this and whether we need to hand it over to someone else.

**Comment by evrardjp** [comment]
Still not merged upstream.

**Comment by evrardjp** [comment]
merged.
