### ISSUE TITLE
L>M Upgrade: Network MTU overrides are not honored

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1484]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

r13.1.0rc1
13.3.4-1-ga489036

##### What type of issue is this? Please tick the appropriate box.
- [X] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

See OSA review https://review.openstack.org/#/c/384635/

##### What is actually happening?

MTU settings are hard coded per https://github.com/rcbops/rpc-openstack/blob/master/scripts/test-upgrade.sh#L101-L102 and we should honor Liberty overrides like neutron_network_device_mtu and container_mtu from the provider networks.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Manually changed the hard coded values to desired MTUs

##### How can we reproduce this issue?

N/A

##### How can we verify your issue is addressed?

MTU is honored according old settings

##### If you are using or know of a workaround please describe the necessary steps?

N/A

##### What is your evaluation on the importance of this issue, and why?

Prio 3

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master https://github.com/rcbops/rpc-openstack/pull/1521
- [x] mitaka-13.1 https://github.com/rcbops/rpc-openstack/pull/1525

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [x] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

https://github.com/rcbops/u-suk-dev/issues/529

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [x] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes): https://github.com/rackerlabs/docs-rpc/pull/663

**Comment by alextricity25** [comment]
@BjoernT, the ``test-script.sh`` script was designed only for gate and dev purposes.
However, it wouldn't be a bad idea to move these lines into a playbook, maybe even the rpc-pre-upgrade.yml playbook. From there it should be easy to reference ``container_mtu``.
If you are interested, the MTU changes are documented here: https://github.com/rackerlabs/docs-rpc/pull/620/files#diff-dd39230c5ac09e679cf15c660ba2de64R210

**Comment by cloudnull** [comment]
In OSA we've identified this as a short coming in our upgrade process and have put this together: [ https://review.openstack.org/#/c/384635/ ]. with a few more reviews we're hoping to have that merged soon.

**Comment by alextricity25** [comment]
Thanks, Kevin! Once this merges in and our SHA is bumped, we can move this out of our documentation and testing script.
