### ISSUE TITLE
qpress lost gpg key in repo

### ISSUE THREAD

**Issue by Frank-ZhangXin** [rcbops/rpc-openstack#1515]
##### On which version(s) do you encounter this issue?
Master
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

> TASK: [galera_server | Check apt last update file] ****************************
> ok: [frank-bug-1448_galera_container-6126ef91]
> 
> TASK: [galera_server | Update apt if needed] **********************************
> ok: [frank-bug-1448_galera_container-6126ef91]
> 
> TASK: [galera_server | Install galera packages] *******************************
> failed: [frank-bug-1448_galera_container-6126ef91] => (item=mariadb-client,mariadb-galera-server-10.0,galera-3,qpress,rsync,socat) => {"attempts": 5, "failed": true, "item": "mariadb-client,mariadb-galera-server-10.0,galera-3,qpress,rsync,socat"}
> stderr: E: There are problems and -y was used without --force-yes
> 
> stdout: Reading package lists...
> Building dependency tree...
> Reading state information...
> The following extra packages will be installed:
>   gawk iproute libhtml-template-perl libsigsegv2 lsof psmisc
> Suggested packages:
>   gawk-doc libipc-sharedcache-perl mailx mariadb-galera-test tinyca
> The following NEW packages will be installed:
>   galera-3 gawk iproute libhtml-template-perl libsigsegv2 lsof
>   mariadb-galera-server-10.0 psmisc qpress socat
> 0 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
> Need to get 18.9 MB of archives.
> After this operation, 136 MB of additional disk space will be used.
> WARNING: The following packages cannot be authenticated!
>   qpress
> 
> msg: Task failed as maximum retries was encountered
> 
> FATAL: all hosts have already failed -- aborting

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
qpress tool should be installed automatically during Install galera packages with additional authentication.

##### What is actually happening?
qpress needs authentication and stop galera installment.

##### How can we reproduce this issue?
On current master branch, AIO deployment with DEPLOY_CEPH and DEPLOY_TEMPEST.

##### What is your evaluation on the importance of this issue, and why?

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master https://github.com/rcbops/rpc-openstack/pull/1521
- [x] mitaka-13.1 https://github.com/rcbops/rpc-openstack/pull/1525
- [x] mitaka-13.0 https://github.com/rcbops/rpc-openstack/pull/1529
- [x] liberty-12.2 https://github.com/rcbops/rpc-openstack/pull/1520

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [x] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [x] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes): https://github.com/rackerlabs/docs-rpc/pull/663

**Comment by Frank-ZhangXin** [comment]
It's also related to upstream bug: https://review.openstack.org/#/c/388205/

**Comment by odyssey4me** [comment]
Mitaka backport: https://review.openstack.org/388499 - that will then need a patch in OSA for a role SHA bump to consume it. I'll handle that once the patch merges.
Liberty backport: https://review.openstack.org/388501 - once that merges, no further OSA patches will be required.

**Comment by git-harry** [comment]
Updating the SHA will pull in the patch ["Update the neutron MTU settings on upgrade"](https://github.com/openstack/openstack-ansible/commit/08ceafa7ae53e9b8b0ccf893768c313ffbc52bc0). I assume that means we need to remove the [equivalent section from the test script](https://github.com/rcbops/rpc-openstack/blob/mitaka-13.1/scripts/test-upgrade.sh#L93-L107) at the same time?

**Comment by odyssey4me** [comment]
Mitaka galera_server patch merged. Integrated repo proposal to include the updates proposed: https://review.openstack.org/388564

**Comment by odyssey4me** [comment]
@git-harry I suspect you are right. cc @evrardjp @mattt416 @alextricity25

**Comment by odyssey4me** [comment]
The Liberty backport has merged.

**Comment by odyssey4me** [comment]
The Mitaka backport has merged.

**Comment by mattt416** [comment]
Correct @git-harry @odyssey4me -- it won't hurt if it's left in but it should come out at the same time if possible.  I can create a patch with the docs team once that all happens.

**Comment by sigmavirus24** [comment]
Just merged #1529
