### ISSUE TITLE
L>M Upgrade: rfc1034_1035-cleanup.yml does not work with insecure public API Edit OSA/#1643727

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1590]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

r13.1.1

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

Play cleans up old , dead agents and service regardless of API/SSL situation

##### What is actually happening?

See https://bugs.launchpad.net/openstack-ansible/+bug/1643727

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

adding --insecure inside the playbook

##### How can we reproduce this issue?

Run play after upgrade against public API with self signed cert

##### How can we verify your issue is addressed?

It cleans up all dead agents/services

##### If you are using or know of a workaround please describe the necessary steps?

Manually removed the entries

##### What is your evaluation on the importance of this issue, and why?

Prio 3

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by b3rnard0** [comment]
@BjoernT Has a workaround for this current issue.

**Comment by cloudnull** [comment]
@BjoernT Being that you have a work around for this, what are the steps you run to resolve the issue? Is this something we could automate in the post_upgrade_role?

**Comment by BjoernT** [comment]
Closing here with reference of the upstream bug
