### ISSUE TITLE
Newton: selective repo-build process still buggy OSA/1649329

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1617]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

You can deploy OSA 14.X without swift hosts

##### What is actually happening?

Repo build process fails

https://bugs.launchpad.net/openstack-ansible/+bug/1649329

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Just running setup-intrastructure on a new install on Ubuntu 14.04

##### How can we reproduce this issue?

See https://bugs.launchpad.net/openstack-ansible/+bug/1649329

##### How can we verify your issue is addressed?

No more repo-build errors

##### If you are using or know of a workaround please describe the necessary steps?

Setting repo_build_git_selective to False

##### What is your evaluation on the importance of this issue, and why?

Prio 1 

Prohibiting 14.x install

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment]
The fix for this upstream has merged. Now we just need a sha bump here to include the fix.

**Comment by odyssey4me** [comment]
@alextricity25 You'll need to wait for the upstream SHA bump before you can do a SHA bump for rpc-openstack to consume it. The current SHA for the role is behind that particular patch.

**Comment by alextricity25** [comment]
I applied the fix to my environment, but the wheel's still don't get built due to another error on the same task. I've put more information here: https://bugs.launchpad.net/openstack-ansible/+bug/1649329

**Comment by alextricity25** [comment]
This PS needs to be reviewed, then backported to newton before this bug is completely fixed:
https://review.openstack.org/#/c/413767/
