### ISSUE TITLE
apt-cacher files have incorrect authorities

### ISSUE THREAD

**Issue by alextricity25** [rcbops/rpc-openstack#1623]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
https://bugs.launchpad.net/openstack-ansible/+bug/1649339
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
https://bugs.launchpad.net/openstack-ansible/+bug/1649339

##### What is actually happening?
https://bugs.launchpad.net/openstack-ansible/+bug/1649339

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
https://bugs.launchpad.net/openstack-ansible/+bug/1649339

##### How can we reproduce this issue?
https://bugs.launchpad.net/openstack-ansible/+bug/1649339

##### How can we verify your issue is addressed?
https://bugs.launchpad.net/openstack-ansible/+bug/1649339

##### If you are using or know of a workaround please describe the necessary steps?
https://bugs.launchpad.net/openstack-ansible/+bug/1649339

##### What is your evaluation on the importance of this issue, and why?
https://bugs.launchpad.net/openstack-ansible/+bug/1649339
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by evrardjp** [comment]
It's definitely something to track in RPC, and fix (if required), depending on how OSA decides to fix it in stable/newton branch. 

Example: If RPC newton is released before OSA patch, and a customer is deployed, then you may have to ship something to get back to OSA standard at some point, which is something to avoid as much as possible.

**Comment by cloader89** [comment]
just backported the change from upstream https://review.openstack.org/#/c/420773/
