### ISSUE TITLE
Newton: Git server not working OSA/1650647

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1637]
##### What type of issue is this? Please tick the appropriate box.
- [X] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

Working git server 

##### What is actually happening?

See https://bugs.launchpad.net/openstack-ansible/+bug/1650647

##### How can we reproduce this issue?

Install Newton on 14.04 

##### How can we verify your issue is addressed?

Git requests are served

##### If you are using or know of a workaround please describe the necessary steps?

N/A

##### What is your evaluation on the importance of this issue, and why?

 Prio 2

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by d34dh0r53** [comment]
The upstream bug has been marked Invalid as it started working after a redeploy.  @BjoernT can we close this or is it still an issue?

**Comment by b3rnard0** [comment]
@rcbops/support-feedback Please provide feedback on @d34dh0r53's comment. Thanks.
