### ISSUE TITLE
ceph_apt_pin_packages default value is incorrect

### ISSUE THREAD

**Issue by alextricity25** [rcbops/rpc-openstack#1638]
##### On which version(s) do you encounter this issue?
Master on newton

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

Upstream Bug:
https://bugs.launchpad.net/openstack-ansible/+bug/1646855

##### What is your evaluation on the importance of this issue, and why?
Prio-3. The incorrect behavior is being overridden in the rpco repo here: https://github.com/rcbops/rpc-openstack/blob/master/rpcd/etc/openstack_deploy/user_osa_variables_defaults.yml#L144
Once the upstream bug has been fixed we should be able to remove the override.
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by major** [comment]
Upstream OSA patch proposed to master branch: https://review.openstack.org/#/c/416602/

**Comment by alextricity25** [comment]
Let's not forget to remove our pin here once this change is backported to stable/newton.
https://github.com/rcbops/rpc-openstack/blob/master/rpcd/etc/openstack_deploy/user_osa_variables_defaults.yml#L144

**Comment by major** [comment]
- [ ] OSA master: https://review.openstack.org/#/c/416602/
- [ ] OSA stable/newton: https://review.openstack.org/#/c/416984/

**Comment by alextricity25** [comment]
@major Before we remove the pin, the role SHAs for newton will need to be updated upstream in the integrated repo. Then the OSA SHA here will need to be updated.

**Comment by major** [comment]
@alextricity25 Good stuff. Updated my checklist. ;)
