### ISSUE TITLE
[Newton-14.0] os_horizon play failing at venv download, causing cascading failures on next 4 tasks

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/rpc-openstack#1786]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
root@node84:/opt/rpc-openstack# git describe --all
heads/newton-14.0

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
[os_horizon: Attempt venv download] retries until successful

##### What is actually happening?
when [os_horizon: Attempt venv download] fails it fails to register horizon_get_env which is a register that the next 4 tasks use, so when it gets to [os_horizon: Create horizon link for venv] any containers that dont have that variable registered will fail

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Install Newton onto a environment with a haproxy loadbalancer which seems to have dropped the venv download package

##### How can we reproduce this issue?
deliberately make the repo server fail to send the venv for the horizon

##### How can we verify your issue is addressed?
ensure that the horizon_get_env register for ansible is set by either making a success boolean or adding retries, or both

##### If you are using or know of a workaround please describe the necessary steps?
currently working on how to get around this, possibly deleting ansible fact cache

##### What is your evaluation on the importance of this issue, and why?
Important, if a install fails to download the venv to a container then horizon is broken

GIST
https://gist.github.com/jacobwagner/e2c3e1072d9338a2c611ac3e6071e0da

This seems to be where the issue lies in the os_horizon task
https://github.com/openstack/openstack-ansible-os_horizon/blob/master/tasks/horizon_install.yml#L78-L84

It seems like a retry / until success block needs to be added to ensure success or outright fail and not register the variable so future runs can succeed

I have filed this upstream as well

https://bugs.launchpad.net/openstack-ansible/+bug/1661374

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] newton-14.0
- [ ] mitaka-13.1
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by jacobwagner** [comment]
@alextricity25 for tracking purposes

**Comment by Frank-ZhangXin** [comment]
Update:
@jacobwagner @alextricity25 
Upstream patch added: https://review.openstack.org/#/c/428794/
Feel free to take a look

**Comment by Frank-ZhangXin** [comment]
Update:
Upstream went well, and will be merged soon.
@alextricity25 do you think later on if sha bump needs including this?

**Comment by alextricity25** [comment]
@Frank-ZhangXin Yes, it will need a OSA SHA bump here. However, the patch set needs to be backported to the OSA stable/newton branch first, then you can move this card over to "Pending SHA Update".

**Comment by Frank-ZhangXin** [comment]
Update:
Backport for newton submitted: https://review.openstack.org/#/c/429784/
