### ISSUE TITLE
Tracking of Repo sync not complete before attempting to install packages

### ISSUE THREAD

**Issue by d34dh0r53** [rcbops/rpc-openstack#877]
##### What version (commit) do you encounter this issue on?
All

##### What type of issue is this (bug, feature, documentation, regression)?
Bug

##### What is the expected behavior?
When there are multiple repo containers, lsync is configured to maintain synchronisation between them.

##### What is actually happening?
there is no check to ensure that the initial synchronisation has completed.

There is then a race between repo sync and the first python package that needs to be installed.

Example Failure:

```
===========================
**06:38:50** TASK: [galera_client | Install pip packages] **********************************
**06:38:50** failed: [jrpcaioiad-bfb_galera_container-28d13a84] => (item=MySQL-python) => {"attempts": 5, "cmd": "/usr/local/bin/pip install MySQL-python", "failed": true, "item": "MySQL-python"}
**06:38:50** msg: Task failed as maximum retries was encountered
**06:38:50** failed: [jrpcaioiad-bfb_galera_container-28d13a84] => (item=python-memcached) => {"attempts": 5, "cmd": "/usr/local/bin/pip install python-memcached", "failed": true, "item": "python-memcached"}
**06:38:50** msg: Task failed as maximum retries was encountered
**06:38:50** failed: [jrpcaioiad-bfb_galera_container-28d13a84] => (item=pycrypto) => {"attempts": 5, "cmd": "/usr/local/bin/pip install pycrypto", "failed": true, "item": "pycrypto"}
**06:38:50** msg: Task failed as maximum retries was encountered
===========================
```

##### How can we reproduce this issue?
This is a race condition so it is not easily reproducible

##### How can we verify your issue is addressed?
This is a tracking bug for OSA issue [`1543146`](https://bugs.launchpad.net/openstack-ansible/+bug/1543146)

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
There is a workaround outlined in the bug report

##### What is your evaluation on the importance of this issue, and why?
Prio-2 this is an installation and upgrade impacting bug

##### What branches / milestones do you believe this issue should target?

OSA
- [x] Master [279452](https://review.openstack.org/#/c/279452/)
- [x] liberty [316033](https://review.openstack.org/#/c/316033/)
- [x] kilo [316032](https://review.openstack.org/#/c/316032/)

RPCO
- [x] master
- [x] liberty-12.2
- [x] liberty-12.1
- [x] kilo

**Comment by d34dh0r53** [comment]
The patch set for this is here [`279452`](https://review.openstack.org/#/c/279452) please review and test when you have time.

**Comment by git-harry** [comment]
This needs backporting in OSA

**Comment by mancdaz** [comment]
Backports for both [liberty](https://review.openstack.org/#/c/316033/) and [kilo](https://review.openstack.org/#/c/316032/) proposed. Depending on how the reviewers feel, this may be deemed inappropriate for kilo given that's it's near EOL, but since it is an isolated change it should hopefully be ok.

**Comment by mancdaz** [comment]
Both backports have merged. OSA sha bumps will take account of including this in the next release(s)
